---
- hosts: spines
  user: admin
  become: yes
  become_method: sudo
  any_errors_fatal: true
  tasks:
    - name: include common variables
      include_vars: "maintanence_vars.yml"
    - name: check for number of redundant paths for specified prefix
      shell: "ip route show {{ test_prefix_fabric }} | grep via | wc -l"
      register: test_prefix_paths
    - name: display the number of redundant to test_prefix
      debug: msg="{{test_prefix_paths.stdout|int}}"
    - name: check if test_prefix_paths < min_redundant_paths
      fail:
        msg: "Paths to {{test_prefix_fabric}} are not redundant! Exiting..."
      when: test_prefix_paths.stdout|int < min_redundant_paths

- hosts: "{{target}}"
  user: admin
  become: yes
  become_method: sudo
  tasks:
    - name: include common variables
      include_vars: "maintanence_vars.yml"
    - name: create filter for AS prepend
      blockinfile:
        insertbefore: '# filters end'
        dest: "/etc/bird.conf"
        block: |
          filter bgp_out {
          bgp_path.prepend({{node[ansible_hostname].BGP.asn}});
          bgp_path.prepend({{node[ansible_hostname].BGP.asn}});
          bgp_path.prepend({{node[ansible_hostname].BGP.asn}});
          }
    - name: higher the OSPF metric on target to drain traffic from servers
      replace:
        dest: "/etc/bird.conf"
        regexp: 'cost \d+; # to_servers'
        replace: 'cost 2000; # to_servers'
        backup: yes
    - service: name=bird state=reloaded
    - pause: seconds=10
    - name: set BGP export with AS prepend filters to drain traffic from fabric
      replace:
        dest: "/etc/bird.conf"
        regexp: 'export all; # to_spines'
        replace: 'export filter bgp_out; # to_spines'
        backup: yes
    - service: name=bird state=reloaded

- hosts: spines
  user: admin
  become: yes
  become_method: sudo
  tasks:
    - name: include common variables
      include_vars: "maintanence_vars.yml"
    - pause: seconds=3
    - debug: msg="ip route show {{test_prefix_fabric}} | egrep via {{node[target].interfaces.swp13.ipv4_addresses[0]|ipaddr('address')}}|via {{node[target].interfaces.swp14.ipv4_addresses[0]|ipaddr('address')}}"
    - name: check if traffic was drained from the target for Fabric
      shell: "ip route show {{test_prefix_fabric}} | egrep 'via {{node[target].interfaces.swp13.ipv4_addresses[0]|ipaddr('address')}}|via {{node[target].interfaces.swp14.ipv4_addresses[0]|ipaddr('address')}}'"
      register: prefix_paths_via_target
      failed_when: "prefix_paths_via_target.rc == 2"
    - debug: msg="Paths for {{test_prefix_fabric}} available via {{target}} - {{prefix_paths_via_target.stdout_lines}}"
    - name: check if there is no any paths available via {{target}}
      assert: { that: "prefix_paths_via_target.stdout == ''"}

- hosts: servers_centos
  user: admin
  become: yes
  become_method: sudo
  tasks:
    - name: include common variables
      include_vars: "maintanence_vars.yml"
    - pause: seconds=3
    - debug: msg="ip route show {{test_prefix_servers}} | egrep via {{node[target].interfaces.swp1s0.ipv4_addresses[0]|ipaddr('address')}}"
    - name: check if traffic was drained from the target for Servers
      shell: "ip route show {{test_prefix_servers}} | egrep 'via {{node[target].interfaces.swp1s0.ipv4_addresses[0]|ipaddr('address')}}'"
      register: prefix_paths_via_target
      failed_when: "prefix_paths_via_target.rc == 2"
    - debug: msg="Paths for {{test_prefix_servers}} available via {{target}} - {{prefix_paths_via_target.stdout_lines}}"
    - name: check if there is no any paths available via {{target}}
      assert: { that: "prefix_paths_via_target.stdout == ''"}
