---
- name: set up routing
  lineinfile:
    dest: "{{sysctl_file}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: "^net.ipv4.ip_forward", line: "net.ipv4.ip_forward = 1"}
    - { regexp: "^net.ipv4.conf.default.rp_filter", line: "net.ipv4.conf.default.rp_filter = 0"}
    - { regexp: "^net.ipv4.tcp_syncookies", line: "net.ipv4.tcp_syncookies = 0"}
    - { regexp: "^net.ipv4.tcp_l3mdev_accept", line: "net.ipv4.tcp_l3mdev_accept = 1"}
    - { regexp: "^net.ipv4.udp_l3mdev_accept", line: "net.ipv4.udp_l3mdev_accept = 1"}
  tags:
    - setup_routing

- name: display ifaces folder
  debug:
    msg: "ifaces_folder: {{ifaces_folder}}"
  tags:
    - ifaces_setup

- name: create ifaces vars
  set_fact:
    ignore_ifaces: "{{global.ignore_ifaces | default([])}}"
    ifaces_all: "{{ ({} | combine(node[ansible_hostname].interfaces.common|default({}),
                node[ansible_hostname].interfaces.bonds|default({}),
                node[ansible_hostname].interfaces.bridges|default({}))) }}"
    ifaces_common: "{{node[ansible_hostname].interfaces.common|default({})}}"
    ifaces_bonds: "{{node[ansible_hostname].interfaces.bonds|default({})}}"
    ifaces_bridges: "{{node[ansible_hostname].interfaces.bridges|default({})}}"
  when: ansible_hostname in node and node[ansible_hostname].interfaces is defined
  tags:
    - ifaces_setup
- name: default ifaces vars if ansible_hostname is not in vars
  set_fact:
    ignore_ifaces: "{{global.ignore_ifaces | default([])}}"
    ifaces_all: "{{ {} }}"
    ifaces_common: "{{ {} }}"
    ifaces_bonds: "{{ {} }}"
    ifaces_bridges: "{{ {} }}"
  when: ansible_hostname not in node
  tags:
    - ifaces_setup
- debug:
    msg:
      - "ignore_ifaces: {{ignore_ifaces}}"
      - "ifaces_common: {{ifaces_common.keys()}}"
      - "ifaces_bonds: {{ifaces_bonds.keys()}}"
      - "ifaces_bridges: {{ifaces_bridges.keys()}}"
  tags:
    - ifaces_setup

- name: collect existing iface folders
  find:
    paths: "{{ifaces_folder}}"
    recurse: false
    file_type: directory
  register: collected_folders
  tags:
    - ifaces_setup
- name: setting existing ifaces facts
  set_fact:
    existing_ifaces: "{{collected_folders.files|map(attribute='path')|map('basename')|list}}"
  tags:
    - ifaces_setup
- name: setting ifaces to remove facts
  set_fact:
    remove_ifaces: "{{existing_ifaces | difference(ifaces_all.keys() | union(ignore_ifaces))}}"
  tags:
    - ifaces_setup
- name: display existing ifaces
  debug:
    var: existing_ifaces
  tags:
    - ifaces_setup
- name: display ifaces to remove
  debug:
    var: remove_ifaces
  tags:
    - ifaces_setup

- name: remove existing iface folders that are not defined in facts
  file:
    path: "{{ifaces_folder}}/{{item}}/"
    state: absent
  tags:
    - ifaces_setup
  with_items: "{{remove_ifaces}}"
  when: ansible_hostname in node
  register: iface_folder_removed_result

- name: create per-iface folders
  file: path="{{ifaces_folder}}/{{item}}" state=directory recurse=yes
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_folder_created_result

- name: create rendered flat-file <iface>/iplink
  template: src=iplink.j2 dest="{{ifaces_folder}}/{{item}}/iplink"
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_iplink_rendered_result

- name: create rendered flat-file <iface>/ipv4address
  template: src=ipv4address.j2 dest="{{ifaces_folder}}/{{item}}/ipv4address"
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_ipv4address_rendered_result

- name: create rendered flat-file <iface>/ipv4route
  template: src=ipv4route.j2 dest="{{ifaces_folder}}/{{item}}/ipv4route"
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_ipv4route_rendered_result

- name: create rendered flat-file <iface>/ifup-pre
  template: src=ifup_pre.j2 dest="{{ifaces_folder}}/{{item}}/ifup-pre" mode=744
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_ifup_pre_rendered_result

- name: create rendered flat-file <iface>/ifup-post
  template: src=ifup_post.j2 dest="{{ifaces_folder}}/{{item}}/ifup-post" mode=744
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_ifup_post_rendered_result

- name: create rendered flat-file <iface>/ifdown-pre
  template: src=ifdown_pre.j2 dest="{{ifaces_folder}}/{{item}}/ifdown-pre" mode=744
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_ifdown_pre_rendered_result

- name: create rendered flat-file <iface>/ifdown-post
  template: src=ifdown_post.j2 dest="{{ifaces_folder}}/{{item}}/ifdown-post" mode=744
  tags:
    - ifaces_setup
  with_items: "{{ifaces_all}}"
  register: iface_ifdown_post_rendered_result

- name: create rendered flat-file <iface>/options for common ifaces
  template: src=options_common.j2 dest={{ifaces_folder}}/{{item}}/options
  tags:
    - ifaces_setup
  with_items: "{{ifaces_common}}"
  register: iface_common_rendered_result

- name: create rendered flat-file <iface>/options for bonds
  template: src=options_bond.j2 dest={{ifaces_folder}}/{{item}}/options
  tags:
    - ifaces_setup
  with_items: "{{ifaces_bonds}}"
  register: iface_bonds_rendered_result

- name: create rendered flat-file <iface>/options for bridges
  template: src=options_bridge.j2 dest={{ifaces_folder}}/{{item}}/options
  tags:
    - ifaces_setup
  with_items: "{{ifaces_bridges}}"
  register: iface_bridges_rendered_result

- name: set configuration changed fact
  set_fact:
    config_changed: "{{iface_folder_removed_result.changed or
                    iface_iplink_rendered_result.changed or
                    iface_ipv4route_rendered_result.changed or
                    iface_folder_created_result.changed or
                    iface_ifup_pre_rendered_result.changed or
                    iface_ifup_post_rendered_result.changed or
                    iface_ifdown_pre_rendered_result.changed or
                    iface_ifdown_post_rendered_result.changed or
                    iface_ipv4address_rendered_result.changed or
                    iface_common_rendered_result.changed or
                    iface_bonds_rendered_result.changed or
                    iface_bridges_rendered_result.changed}}"
  tags:
    - ifaces_setup

- name: restart network if configuration is changed
  service: name=network state=restarted
  when: config_changed
  tags:
    - ifaces_setup
